spring:
    application:
        name: usuarios-api
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: none
    # Propriedades de conexão com o banco de dados
    datasource:
        url: jdbc:mysql://localhost:3306/usuarios_api
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver


    
# Porta onde é executada a aplicação
server:
    port: 8081

